import { Ingredients } from '../imports/api/ingredients.js';

Meteor.startup(function () {
  if (Ingredients.find().count() === 0) {
    console.log("Seeding ingredients");
    [
      { name: "cilantro lime rice", size: "small", calories: 95.6, checked: false },
      { name: "brown rice", size: "small", calories: 122.7, checked: false },
      { name: "whole wheat tortilla", size: "small", calories: 196.5, checked: false },
      { name: "flour tortilla", size: "small", calories: 210.3, checked: false },
      { name: "caramelized onions", size: "small", calories: 20.0, checked: false },
      { name: "curried chick peas", size: "small", calories: 56.7, checked: false },
      { name: "black beans", size: "small", calories: 42.8, checked: false },
      { name: "buffalo sauce", size: "small", calories: 31.5, checked: false },
      { name: "thai-style peanut sauce", size: "small", calories: 75.0, checked: false },
      { name: "asian vinaigrette", size: "small", calories: 70.9, checked: false },
      { name: "tikka masala sauce", size: "small", calories: 45.1, checked: false },
      { name: "yogurt raita sauce", size: "small", calories: 15.6, checked: false },
      { name: "teriyaki sauce", size: "small", calories: 35.4, checked: false },
      { name: "mango salsa", size: "small", calories: 32.2, checked: false },
      { name: "skinny mediterranean vinaigrette", size: "small", calories: 41.8, checked: false },
      { name: "pico de gallo", size: "small", calories: 11.3, checked: false },
      { name: "house made hummus", size: "small", calories: 87.1, checked: false },
      { name: "corn salsa", size: "small", calories: 59.1, checked: false },
      { name: "rice noodles", size: "small", calories: 98.7, checked: false },
      { name: "almonds", size: "small", calories: 81.5, checked: false },
      { name: "jack cheese", size: "small", calories: 101.3, checked: false },
      { name: "feta cheese", size: "small", calories: 46.5, checked: false },
      { name: "blue cheese celery slaw", size: "small", calories: 68.0, checked: false },
      { name: "sour cream", size: "small", calories: 48.4, checked: false },
      { name: "cucumber", size: "small", calories: 2.6, checked: false },
      { name: "shredded carrots", size: "small", calories: 7.4, checked: false },
      { name: "scallions", size: "small", calories: 2.8, checked: false },
      { name: "romaine lettuce", size: "small", calories: 4.8, checked: false },
      { name: "grilled chicken", size: "small", calories: 60.0, checked: false },
      { name: "cilantro lime rice", size: "regular", calories: 159.3, checked: false },
      { name: "flour tortilla", size: "regular", calories: 310.2, checked: false },
      { name: "brown rice", size: "regular", calories: 204.5, checked: false },
      { name: "caramelized onions", size: "regular", calories: 40.0, checked: false },
      { name: "whole wheat tortilla", size: "regular", calories: 290.0, checked: false },
      { name: "curried chick peas", size: "regular", calories: 113.5, checked: false },
      { name: "black beans", size: "regular", calories: 85.5, checked: false },
      { name: "tikka masala sauce", size: "regular", calories: 67.6, checked: false },
      { name: "yogurt raita sauce", size: "regular", calories: 23.4, checked: false },
      { name: "teriyaki sauce", size: "regular", calories: 53.2, checked: false },
      { name: "asian vinaigrette", size: "regular", calories: 94.5, checked: false },
      { name: "mango salsa", size: "regular", calories: 64.5, checked: false },
      { name: "skinny mediterranean vinaigrette", size: "regular", calories: 62.7, checked: false },
      { name: "corn salsa", size: "regular", calories: 118.2, checked: false },
      { name: "thai-style peanut sauce", size: "regular", calories: 112.6, checked: false },
      { name: "buffalo sauce", size: "regular", calories: 63.0, checked: false },
      { name: "pico de gallo", size: "regular", calories: 22.7, checked: false },
      { name: "house made hummus", size: "regular", calories: 174.2, checked: false },
      { name: "rice noodles", size: "regular", calories: 98.7, checked: false },
      { name: "almonds", size: "regular", calories: 81.5, checked: false },
      { name: "jack cheese", size: "regular", calories: 151.9, checked: false },
      { name: "blue cheese celery slaw", size: "regular", calories: 136.0, checked: false },
      { name: "feta cheese", size: "regular", calories: 93.0, checked: false },
      { name: "sour cream", size: "regular", calories: 96.7, checked: false },
      { name: "shredded carrots", size: "regular", calories: 14.9, checked: false },
      { name: "scallions", size: "regular", calories: 2.8, checked: false },
      { name: "cucumber", size: "regular", calories: 3.4, checked: false },
      { name: "romaine lettuce", size: "regular", calories: 7.2, checked: false },
      { name: "grilled chicken", size: "regular", calories: 120.0, checked: false },
      { name: "cilantro lime rice", size: "bowl", calories: 191.2, checked: false },
      { name: "brown rice", size: "bowl", calories: 245.4, checked: false },
      { name: "caramelized onions", size: "bowl", calories: 26.6, checked: false },
      { name: "curried chick peas", size: "bowl", calories: 113.5, checked: false },
      { name: "black beans", size: "bowl", calories: 85.5, checked: false },
      { name: "tikka masala sauce", size: "bowl", calories: 67.6, checked: false },
      { name: "yogurt raita sauce", size: "bowl", calories: 23.4, checked: false },
      { name: "teriyaki sauce", size: "bowl", calories: 53.2, checked: false },
      { name: "asian vinaigrette", size: "bowl", calories: 94.5, checked: false },
      { name: "mango salsa", size: "bowl", calories: 64.5, checked: false },
      { name: "buffalo sauce", size: "bowl", calories: 63.0, checked: false },
      { name: "pico de gallo", size: "bowl", calories: 22.7, checked: false },
      { name: "house made hummus", size: "bowl", calories: 174.2, checked: false },
      { name: "skinny mediterranean vinaigrette", size: "bowl", calories: 62.7, checked: false },
      { name: "corn salsa", size: "bowl", calories: 118.2, checked: false },
      { name: "thai-style peanut sauce", size: "bowl", calories: 112.6, checked: false },
      { name: "rice noodles", size: "bowl", calories: 98.7, checked: false },
      { name: "almonds", size: "bowl", calories: 81.5, checked: false },
      { name: "jack cheese", size: "bowl", calories: 151.9, checked: false },
      { name: "sour cream", size: "bowl", calories: 96.7, checked: false },
      { name: "blue cheese celery slaw", size: "bowl", calories: 136.0, checked: false },
      { name: "feta cheese", size: "bowl", calories: 93.0, checked: false },
      { name: "shredded carrots", size: "bowl", calories: 14.9, checked: false },
      { name: "scallions", size: "bowl", calories: 2.8, checked: false },
      { name: "cucumber", size: "bowl", calories: 3.4, checked: false },
      { name: "romaine lettuce", size: "bowl", calories: 7.2, checked: false },
      { name: "grilled chicken", size: "bowl", calories: 120.0, checked: false }
    ].forEach(function(ing) {
      Ingredients.insert(ing);
    });
  } else {
    console.log(Ingredients.find().count() + " ingredients found, starting server");
  }
});
